version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: pg-shipment
    restart: always
    environment:
      POSTGRES_DB: shipmentdb
      POSTGRES_USER: shipment
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shipment -d shipmentdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - delivery-net

  courier-db:
    image: postgres:16
    container_name: courier-db
    restart: always
    environment:
      POSTGRES_DB: courierdb
      POSTGRES_USER: courier
      POSTGRES_PASSWORD: courier
    ports:
      - "5434:5432"
    volumes:
      - courier_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U courier -d courierdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - delivery-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - delivery-net

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - delivery-net

  shipment-service:
    build: ./shipment-service
    container_name: shipment-service
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://pg-shipment:5432/shipmentdb
      SPRING_DATASOURCE_USERNAME: shipment
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - delivery-net

  notification-service:
    build: ./notification-service
    container_name: notification-service
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - delivery-net

  courier-service:
    build: ./courier-service
    container_name: courier-service
    restart: always
    ports:
      - "8083:8083"
    depends_on:
      courier-db:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://courier-db:5432/courierdb
      SPRING_DATASOURCE_USERNAME: courier
      SPRING_DATASOURCE_PASSWORD: courier
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - delivery-net

  api-gateway:
    build: ./gateway-service
    container_name: api-gateway
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - shipment-service
      - courier-service
    networks:
      - delivery-net

volumes:
  postgres_data:
  courier_data:

networks:
  delivery-net:
    driver: bridge