version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: pg-shipment
    restart: always
    environment:
      POSTGRES_DB: shipmentdb
      POSTGRES_USER: shipment
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shipment -d shipmentdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - delivery-net

  courier-db:
    image: postgres:16
    container_name: courier-db
    restart: always
    environment:
      POSTGRES_DB: courierdb
      POSTGRES_USER: courier
      POSTGRES_PASSWORD: courier
    ports:
      - "5434:5432"
    volumes:
      - courier_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U courier -d courierdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - delivery-net

  notification-db:
    image: postgres:16
    container_name: notification-db
    restart: always
    environment:
      POSTGRES_DB: notificationdb
      POSTGRES_USER: notification
      POSTGRES_PASSWORD: 12345
    ports:
      - "5435:5432"
    volumes:
      - notification_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notification -d notificationdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - delivery-net

  auth-db:
    image: postgres:16
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
    ports:
      - "5436:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d authdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - delivery-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-shipment
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@delivery.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
      courier-db:
        condition: service_healthy
      notification-db:
        condition: service_healthy
      auth-db:
        condition: service_healthy
    networks:
      - delivery-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - delivery-net

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - delivery-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: always
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: delivery-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - delivery-net

  shipment-service:
    build: ./shipment-service
    container_name: shipment-service
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://pg-shipment:5432/shipmentdb
      SPRING_DATASOURCE_USERNAME: shipment
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - delivery-net

  courier-service:
    build: ./courier-service
    container_name: courier-service
    restart: always
    ports:
      - "8083:8083"
    depends_on:
      courier-db:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://courier-db:5432/courierdb
      SPRING_DATASOURCE_USERNAME: courier
      SPRING_DATASOURCE_PASSWORD: courier
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - delivery-net

  notification-service:
    build: ./notification-service
    container_name: notification-service
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      kafka:
        condition: service_started
      notification-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://notification-db:5432/notificationdb
      SPRING_DATASOURCE_USERNAME: notification
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - delivery-net

  auth-service:
    build: ./auth-service
    container_name: auth-service
    restart: always
    ports:
      - "8084:8084"
    depends_on:
      auth-db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/authdb
      SPRING_DATASOURCE_USERNAME: auth_user
      SPRING_DATASOURCE_PASSWORD: auth_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - delivery-net

  api-gateway:
    build: ./gateway-service
    container_name: api-gateway
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - shipment-service
      - courier-service
      - notification-service
      - auth-service
    networks:
      - delivery-net

volumes:
  postgres_data:
  courier_data:
  notification_data:
  auth_data:

networks:
  delivery-net:
    driver: bridge